openapi: 3.0.3
info:
  title: Encrypt Decrypt message
  description: POC para mostrar la funcionalidad de encriptacion y desencriptacion de mensajes
  termsOfService: http://swagger.io/terms/
  contact:
    email: edjacome@pichincha.com
  version: 0.0.1
servers:
  - url: http://localhost:8080/v1
tags:
  - name: person
    description: Administracion de personas
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /cliente:
    post:
      tags:
        - cliente
      summary: Add a new cliente
      description: Add a new cliente
      operationId: addCliente
      requestBody:
        description: Create a new cliente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteDto'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteDto'
        '405':
          description: Invalid input
    put:
      tags:
        - cliente
      summary: Update an existing cliente
      description: Update an existing cliente by Id
      operationId: updateCliente
      requestBody:
        description: Update an existent cliente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteDto'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteDto'
        '400':
          description: Invalid ID supplied
        '404':
          description: Cliente not found
        '405':
          description: Validation exception
    get:
      tags:
        - cliente
      summary: Get all clientes
      description: Get a list of all clientes
      operationId: getAllClientes
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClienteDto'
  /person:
    put:
      tags:
        - person
      summary: Update an existing person
      description: Update an existing person by Id
      operationId: updatePerson
      requestBody:
        description: Update an existent person
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonDto'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDto'            
        '400':
          description: Invalid ID supplied
        '404':
          description: Person not found
        '405':
          description: Validation exception
    post:
      tags:
        - person
      summary: Add a new person
      description: Add a new person
      operationId: addPerson
      requestBody:
        description: Create a new person
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonDto'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDto'
        '405':
          description: Invalid input
  /person/{firstName}:
    get:
      tags:
        - person
      summary: Finds Person by name
      description: Get person by name
      operationId: findPersonByName
      parameters:
        - name: firstName
          in: path
          description: Name values that need to be considered for filter
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonDto'            
        '400':
          description: Invalid name value
    
components:
  schemas:
    PayloadDto:
      type: object
      properties:
        messageUuuid:
          type: string
        key:
          type: string
        body:
          type: string
    PersonDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        phone:
          type: string
          example: '12345'
    ClienteDto:
      type: object
      properties:
        fechaNacimiento:
          type: string
          format: date
          example: '1990-03-12'
          description: 'Fecha de nacimiento en formato YYYY-MM-DD.'
        sujetoCredito:
          type: boolean
          example: true
          description: 'Indica si el cliente es sujeto de crédito.'
        idCliente:
          type: integer
          format: int64
          example: 1
          description: 'Identificador único del cliente.'
        apellidos:
          type: string
          example: 'González'
          description: 'Apellidos del cliente.'
        direccion:
          type: string
          example: 'Calle 123, Apt. 456'
          description: 'Dirección del cliente.'
        estadoCivil:
          type: string
          example: 'Soltero'
          description: 'Estado civil del cliente.'
        identificacion:
          type: string
          example: '1053456789'
          description: 'Número de identificación del cliente.'
          pattern: '^\d{10}$'
        identificacionConyugue:
          type: string
          example: '75105163'
          description: 'Número de identificación del cónyuge.'
          pattern: '^\d{10}$'
        nombreConyugue:
          type: string
          example: 'Adriana Posada'
          description: 'Nombre del cónyuge.'
          minLength: 2
          maxLength: 150
        nombres:
          type: string
          example: 'Carlos'
          description: 'Nombres del cliente.'
          minLength: 2
          maxLength: 150
        telefono:
          type: string
          example: '555-1234'
          description: 'Número de teléfono del cliente.'
      
   
 